dist: trusty
sudo: true
language: c

compiler:
  - gcc
  - clang

#env:
#  - FLB_MEM="-DFLB_JEMALLOC=On"
#  - FLB_MEM="-DFLB_JEMALLOC=Off"
#  - DO_DOCKER=1

before_script:

matrix:
  include:
    - os: linux
      env: FLB_MEM="-DFLB_JEMALLOC=On"
    - os: linux
      env: FLB_MEM="-DFLB_JEMALLOC=Off"
    - os: osx
      env: FLB_MEM="-DFLB_JEMALLOC=Off"
    - os: linux
      language: node_js
        - "9"
      compiler: gcc
      env: DOCKER_BUILD=1
      script: |
        echo "===== BUILD DOCKER IMAGE ======="
        docker build -t test-image -f Dockerfile .
        npm install -g bats

script: |
    ci/do-ut
